### PR TITLE
Update README URLs based on HTTP redirects

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein
### GitHub Corrected URLs

| Was | Now |
| --- | --- |
| https://github.com/johnpapa/angularjs-styleguide#readme | https://github.com/johnpapa/angular-styleguide#readme |
| https://github.com/rwldrn/idiomatic.js#readme | https://github.com/rwaldron/idiomatic.js#readme |
### Other Corrected URLs

| Was | Now |
| --- | --- |
| http://en.wikibooks.org/wiki/Web_Application_Security_Guide/Checklist | https://en.wikibooks.org/wiki/Web_Application_Security_Guide/Checklist |
| http://msdn.microsoft.com/en-us/library/ff926074.aspx | https://msdn.microsoft.com/en-us/library/ff926074.aspx |
| http://msdn.microsoft.com/en-us/library/ms229042.aspx | https://msdn.microsoft.com/en-us/library/ms229042.aspx |
| https://design.atlassian.com/latest/product/foundations/writing-style/ | https://design.atlassian.com/product/foundations/writing-style/ |

### CODE REVIEW

**Comment by ReadmeCritic** [comment]
@NARKOZ should be ready to merge

**Comment by NARKOZ** [comment]
It didn't detect all redirects. 
For example http://google-styleguide.googlecode.com/svn/trunk/shell.xml

**Comment by ReadmeCritic** [comment]
Yeah, it can only detect http redirects (that one is done another way)

**Comment by NARKOZ** [comment]
It's done via meta refresh 

``` html
<!DOCTYPE html>
<meta charset="utf-8">
<meta http-equiv="Refresh" content="1; URL=https://google.github.io/styleguide/shell.xml">
<title>shell.xml</title>
```

Thanks anyway.

**Comment by ReadmeCritic** [comment]
ic thx

**Pull request merged**
